import { StyleSheet } from "react-native";
import { createThemedStyles } from "../ui/theme";

export const chatScreenStyles = createThemedStyles((colors) => ({
  screen: { flex: 1, backgroundColor: colors.canvas },
  header: { height: 58, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.canvas },
  headerTitle: { flex: 1, alignItems: "center", paddingHorizontal: 8 },
  headerActions: { flexDirection: "row", alignItems: "center" },
  headerPageButton: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 6 },
  headerPageButtonActive: { backgroundColor: colors.subtle },
  headerPageBadge: { position: "absolute", top: 1, right: 0, minWidth: 15, height: 15, paddingHorizontal: 3, alignItems: "center", justifyContent: "center", borderRadius: 6, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.canvas, backgroundColor: colors.badge },
  headerPageBadgeText: { color: colors.onBadge, fontSize: 9, lineHeight: 11, fontWeight: "700", letterSpacing: 0 },
  title: { color: colors.ink, fontSize: 15, lineHeight: 20, fontWeight: "600", letterSpacing: 0 },
  statusLine: { flexDirection: "row", alignItems: "center", maxWidth: "100%", marginTop: 1 },
  statusDot: { width: 6, height: 6, borderRadius: 3, marginRight: 5 },
  subtitle: { color: colors.inkMuted, fontSize: 11, lineHeight: 15, letterSpacing: 0 },
  iconButton: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 6 },
  iconDisabled: { opacity: 0.35 },
  iconPressed: { backgroundColor: colors.pressed },
  notice: { minHeight: 40, paddingHorizontal: 16, paddingVertical: 9, flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: colors.warningSoft, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.warning },
  noticePressed: { opacity: 0.75 },
  noticeText: { flex: 1, color: colors.warning, fontSize: 12, lineHeight: 17, letterSpacing: 0 },
  pager: { flex: 1 },
  listContent: { paddingHorizontal: 16, paddingTop: 22, paddingBottom: 28 },
  emptyListContent: { flexGrow: 1 },
  emptyState: { flex: 1, alignItems: "center", justifyContent: "center", paddingBottom: 48 },
  codexMark: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.subtle },
  emptyTitle: { color: colors.ink, fontSize: 18, lineHeight: 24, fontWeight: "600", letterSpacing: 0, marginTop: 15 },
  userRow: { alignItems: "flex-end", marginBottom: 22 },
  userBubble: { position: "relative", maxWidth: "88%", borderRadius: 8, backgroundColor: colors.userBubble, paddingHorizontal: 14, paddingVertical: 10 },
  userBubbleTail: { position: "absolute", top: 12, right: -8, width: 0, height: 0, borderTopWidth: 7, borderBottomWidth: 7, borderLeftWidth: 9, borderTopColor: "transparent", borderBottomColor: "transparent", borderLeftColor: colors.userBubble },
  failedBubble: { backgroundColor: colors.dangerSoft, borderWidth: 1, borderColor: colors.danger },
  userText: { color: colors.ink, fontSize: 15, lineHeight: 22, letterSpacing: 0 },
  messageImages: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 8 },
  messageImage: { width: 148, height: 108, borderRadius: 6, backgroundColor: colors.subtle },
  messageFiles: { gap: 6, marginTop: 8 },
  messageFile: { width: 240, maxWidth: "100%", minHeight: 48, flexDirection: "row", alignItems: "center", paddingHorizontal: 9, paddingVertical: 7, borderWidth: 1, borderColor: colors.userBubbleBorder, borderRadius: 6, backgroundColor: colors.surface },
  messageFilePressed: { opacity: 0.72 },
  messageFileIcon: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 5, backgroundColor: colors.subtle },
  messageFileText: { flex: 1, minWidth: 0, marginLeft: 8 },
  messageFileName: { color: colors.ink, fontSize: 12, lineHeight: 16, fontWeight: "600", letterSpacing: 0 },
  messageFileSize: { color: colors.inkMuted, fontSize: 10, lineHeight: 14, marginTop: 1, letterSpacing: 0 },
  imagePreview: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20, backgroundColor: colors.preview },
  previewImage: { width: "100%", height: "100%" },
  previewActions: { position: "absolute", top: 38, right: 58, flexDirection: "row", gap: 8 },
  previewAction: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 6, backgroundColor: colors.previewControl },
  previewActionPressed: { backgroundColor: colors.previewControlPressed },
  previewClose: { position: "absolute", top: 48, right: 20 },
  pendingLabel: { color: colors.inkFaint, fontSize: 10, lineHeight: 14, marginTop: 5, letterSpacing: 0 },
  failedLabel: { color: colors.danger },
  assistantRow: { minWidth: 0, marginBottom: 20 },
  assistantText: { color: colors.ink, fontSize: 15, lineHeight: 23, letterSpacing: 0 },
  generatedImages: { width: "100%", marginTop: 8, gap: 8 },
  generatedImageButton: { width: "100%", maxWidth: 420, aspectRatio: 4 / 3, overflow: "hidden", borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 7, backgroundColor: colors.subtle },
  generatedImagePressed: { opacity: 0.88 },
  generatedImage: { width: "100%", height: "100%" },
  generatedImageStatus: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, alignItems: "center", justifyContent: "center", gap: 7 },
  generatedImageError: { color: colors.inkMuted, fontSize: 11, lineHeight: 15, letterSpacing: 0 },
  activityRow: { marginBottom: 18 },
  activityHeader: { flexDirection: "row", alignItems: "flex-start" },
  activityIcon: { width: 26, height: 26, borderRadius: 5, alignItems: "center", justifyContent: "center", marginRight: 9 },
  activityBody: { flex: 1, minWidth: 0, paddingTop: 2 },
  activityTitle: { color: colors.ink, fontSize: 13, lineHeight: 18, fontWeight: "600", letterSpacing: 0 },
  activityContent: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: 7, letterSpacing: 0 },
  requestCard: { marginBottom: 22, borderWidth: 1, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface, padding: 14 },
  requestHeading: { flexDirection: "row", alignItems: "center" },
  requestIcon: { width: 30, height: 30, borderRadius: 6, alignItems: "center", justifyContent: "center", marginRight: 10 },
  requestHeadingText: { flex: 1, minWidth: 0 },
  requestTitle: { color: colors.ink, fontSize: 14, lineHeight: 19, fontWeight: "600", letterSpacing: 0 },
  requestMeta: { color: colors.inkMuted, fontSize: 11, lineHeight: 15, marginTop: 1, letterSpacing: 0 },
  requestDetail: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: 12, padding: 10, borderRadius: 5, backgroundColor: colors.subtle, letterSpacing: 0 },
  requestActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8, marginTop: 14 },
  secondaryAction: { minWidth: 72, height: 36, paddingHorizontal: 14, borderRadius: 6, borderWidth: 1, borderColor: colors.borderStrong, alignItems: "center", justifyContent: "center" },
  secondaryActionPressed: { backgroundColor: colors.pressed },
  secondaryActionText: { color: colors.ink, fontSize: 13, lineHeight: 18, fontWeight: "600", letterSpacing: 0 },
  primaryAction: { minWidth: 78, height: 36, paddingHorizontal: 14, borderRadius: 6, flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center", backgroundColor: colors.solid },
  primaryActionPressed: { opacity: 0.82 },
  primaryActionText: { color: colors.onSolid, fontSize: 13, lineHeight: 18, fontWeight: "600", letterSpacing: 0 },
  actionDisabled: { opacity: 0.35 },
  operationMessage: { color: colors.info, fontSize: 11, lineHeight: 16, marginTop: 9, letterSpacing: 0 },
  operationError: { color: colors.danger },
  question: { marginTop: 14 },
  questionHeader: { color: colors.inkMuted, fontSize: 11, lineHeight: 15, fontWeight: "600", textTransform: "uppercase", letterSpacing: 0 },
  questionText: { color: colors.ink, fontSize: 13, lineHeight: 19, marginTop: 3, letterSpacing: 0 },
  optionList: { gap: 7, marginTop: 9 },
  option: { minHeight: 42, borderWidth: 1, borderColor: colors.border, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 8, flexDirection: "row", alignItems: "center" },
  optionSelected: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  optionPressed: { opacity: 0.75 },
  radio: { width: 16, height: 16, borderRadius: 8, borderWidth: 1, borderColor: colors.borderStrong, alignItems: "center", justifyContent: "center", marginRight: 9 },
  radioSelected: { borderColor: colors.accent },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accent },
  optionTextWrap: { flex: 1, minWidth: 0 },
  optionLabel: { color: colors.ink, fontSize: 12, lineHeight: 17, fontWeight: "600", letterSpacing: 0 },
  optionDescription: { color: colors.inkMuted, fontSize: 11, lineHeight: 15, marginTop: 1, letterSpacing: 0 },
  answerInput: { height: 42, marginTop: 9, borderWidth: 1, borderColor: colors.border, borderRadius: 6, paddingHorizontal: 11, color: colors.ink, backgroundColor: colors.surface, fontSize: 13, letterSpacing: 0 },
  composerWrap: { paddingHorizontal: 12, paddingTop: 4, paddingBottom: 6, backgroundColor: colors.canvas },
  attachmentList: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 6 },
  attachmentChip: { maxWidth: "100%", height: 32, flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 6, backgroundColor: colors.surface },
  attachmentName: { maxWidth: 220, color: colors.ink, fontSize: 12, lineHeight: 16, letterSpacing: 0 },
  composerHint: { color: colors.warning, fontSize: 11, lineHeight: 15, marginBottom: 5, paddingHorizontal: 4, letterSpacing: 0 },
  composer: { minHeight: 44, maxHeight: 132, flexDirection: "row", alignItems: "flex-end", borderWidth: 1, borderColor: colors.borderStrong, borderRadius: 8, backgroundColor: colors.surface, paddingLeft: 12, paddingRight: 5, paddingVertical: 4 },
  composerDisabled: { backgroundColor: colors.subtle, borderColor: colors.border },
  composerInput: { flex: 1, minHeight: 32, maxHeight: 112, paddingTop: 5, paddingBottom: 4, paddingRight: 7, color: colors.ink, fontSize: 14, lineHeight: 20, letterSpacing: 0 },
  composerActions: { flexDirection: "row", alignItems: "center", gap: 5 },
  attachButton: { width: 32, height: 32, borderRadius: 6, alignItems: "center", justifyContent: "center" },
  attachmentMenuScrim: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, backgroundColor: colors.overlay },
  attachmentMenu: { position: "absolute", right: 0, bottom: 0, left: 0, borderTopLeftRadius: 8, borderTopRightRadius: 8, backgroundColor: colors.surface, paddingHorizontal: 18, paddingTop: 8, paddingBottom: 18 },
  attachmentMenuHandle: { width: 36, height: 4, alignSelf: "center", borderRadius: 2, backgroundColor: colors.borderStrong },
  attachmentMenuTitle: { marginTop: 12, color: colors.ink, fontSize: 15, lineHeight: 21, fontWeight: "600", textAlign: "center", letterSpacing: 0 },
  attachmentMenuOptions: { flexDirection: "row", justifyContent: "space-around", marginTop: 18, marginBottom: 14 },
  attachmentMenuOption: { width: 76, alignItems: "center", paddingVertical: 6, borderRadius: 6 },
  attachmentMenuIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.subtle },
  attachmentMenuOptionText: { marginTop: 7, color: colors.ink, fontSize: 13, lineHeight: 18, letterSpacing: 0 },
  attachmentMenuCancel: { height: 42, alignItems: "center", justifyContent: "center", borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
  attachmentMenuCancelText: { color: colors.ink, fontSize: 14, lineHeight: 19, fontWeight: "600", letterSpacing: 0 },
  stopButton: { width: 32, height: 32, borderRadius: 6, alignItems: "center", justifyContent: "center", backgroundColor: colors.subtle },
  sendButton: { width: 32, height: 32, borderRadius: 6, alignItems: "center", justifyContent: "center", backgroundColor: colors.solid },
  sendButtonDisabled: { backgroundColor: colors.borderStrong, opacity: 0.55 },
  sendButtonPressed: { opacity: 0.78 },
}));
