proxy_http_version 1.1;
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Authorization $http_authorization;
proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $rhzy_connection_upgrade;
proxy_hide_header Server;
proxy_intercept_errors off;
